version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: circleci/node:16
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: ecommercedb
          POSTGRES_USER: andelarwanda 
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_HOST: ${POSTGRES_HOST}
          POSTGRES_DIALECT: postgres
          NODE_ENV: development
          repo_token: cQeNnS5pEVJZWrEQ1KPoAtaJG7MK4rUGn
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command:  npm install 
      - run:
          name: Install npm dev dependencies
          command: npm install mocha c8 chai-http chai coveralls
      - run:
          name: Run Unit Tests
          command: npm run coverage
      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info
workflows:
  build_tests:
    jobs:
      - run_tests
