version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: circleci/node:16
    environment:
      repo_token: cQeNnS5pEVJZWrEQ1KPoAtaJG7MK4rUGn
      DB_NAME: my_database_name
      DB_USER: my_database_user
      DB_PASS: my_database_password
      DB_HOST: my_database_host
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command:  npm install 
      - run:
          name: Install npm dev dependencies
          command: npm install mocha c8 chai-http chai coveralls
      - run:
          name: Run Unit Tests
          command: npm run coverage
      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info
workflows:
  build_tests:
    jobs:
      - run_tests
